on: [push]
name: Backward compatibility check

jobs:
  bc_check:
    name: Backward compatibility check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      # User in the container seems to be different from the cloned repo's owner.
      # Git doesn't like that as the repo will then be unusable by the owner.
      # We don't care about this here since this is only used for running one test.
      # See https://github.com/actions/runner/issues/2033
      - name: Workaround directory permissions
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      - name: BC Check
        uses: docker://nyholm/roave-bc-check-ga
